### ISSUE TITLE
[downloader] Download implementation

### ISSUE THREAD

**Issue by violet-dev** [project-violet/violet#10]
- [x] Pixiv
 - [ ] Pixiv Gif (Ugoira)
 - [x] Gelbooru
 - [x] Instagram
 - [ ] Twitter
 - [x] Hitomi.la
 - [ ] E-Hentai, ExHentai

If you want to add other downloaders, write comment here.

**Comment by hohommx2015** [comment]
Vote for Pixiv,Pixiv gif,Gelbooru,Ex and E- hentai.

Btw I can not download from hitomi,Download button is grey no reaction to my tap
![S00724-09054450](https://user-images.githubusercontent.com/23112624/88352626-0c771600-cd20-11ea-84b9-247e08615435.jpg)

**Comment by violet-dev** [comment]
Hi
there are some problems, hitomi/eh/exh is not implemented currently.
i will implement it asap

**Comment by violet-dev** [comment]
Added in version 0.8.2.

**Comment by violet-dev** [comment]
default download directory: external storage/Violet/*

**Comment by hohommx2015** [comment]
Button now become purple but download won't start

**Comment by violet-dev** [comment]
Please check your `storage permissions` for violet-app
At the start of download, it will be downloaded immediately without any notice.
You can check the download items on the `Download` tab

**Comment by hohommx2015** [comment]
Gave the permission but doesn't work,it's no problem on your side? Probably my phone's issue

**Comment by violet-dev** [comment]
Please choose the correct symptom from the following examples.
First, check your violet-app verison is 0.8.3, if you are not, download this apk https://github.com/project-violet/violet/releases/tag/0.8.3

1. Nothing happens when I tap the download button. No events are fired.
2. Press the download button and then the article information window will come down. However, nothing is added to the Downloader tab.
3. The download item is added to the Downloader tab, but the download does not proceed.
4. The progress bar of the downloader stays at 0 like `State: [0/333]`.

What is your problem?

**Comment by hohommx2015** [comment]
Version: 0.8.3
symptom: 1

**Comment by violet-dev** [comment]
This is probably because you tried to download immediately without opening the download tab.
Before using the downloader, you need to open the download tab and initialize it.

https://github.com/project-violet/violet/blob/dev/lib/pages/article_info/article_info_page.dart#L226

```dart
                    onPressed: () async {
                      if (!DownloadPageManager.downloadPageLoaded) {
                        return;
                      }
                      await DownloadPageManager.appendTask(
                          'https://hitomi.la/galleries/' +
                              queryResult.id().toString() +
                              '.html');
                      Navigator.pop(context);
                    },
```
This code is download button pressing event.
If `DownloadPageManager.downloadPageLoaded` is false, then any ohter code is not run.

**Comment by hohommx2015** [comment]
>you need to open the download tab and initialize
Thanks, it works now

**Comment by hohommx2015** [comment]
I noticed you have to open the download tab first every time before you want to download anything, can you improve that, thanks.

**Comment by violet-dev** [comment]
I will pop up a message `you must open download tab`.
Thank you reporting!

**Comment by violet-dev** [comment]
I moved the downloader to a separate project.
The downloader is closed source and freely available on the `Google Play Store`.
Check this https://play.google.com/store/apps/details?id=xyz.violet.communitydownloader
