### ISSUE TITLE
다운로드 페이지 개선안

### ISSUE THREAD

**Issue by violet-dev** [project-violet/violet#101]

**Comment by Fgogg** [comment]
-다운로드 경로가 안드로이드 보안정책에 따라 일반적 열람 불가능
-내부경로 사용 해제 후 경로를 다른 내부 경로로 사용해도 다운로드 진행x
-/storage/emulated/0/Android/data/xyz.project.violet/files 기본 경로 말고 Android폴더를 제외한 다른 폴더 사용을 요청

**Comment by violet-dev** [comment]
@Fgogg  https://stackoverflow.com/questions/62782648/android-11-scoped-storage-permissions 적용해보겠습니다
