### ISSUE TITLE
버전업데이트시 다운로드 폴더에 app-release.apk 파일이 이미 존재하면 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by Zerstorer23** [project-violet/violet#111]
버전업데이트시 다운로드 폴더에 app-release.apk 파일이 이미 존재하면 다운로드가 안됩니다.
그리고 업데이트후 apk파일이 다운로드 폴더에 그대로 남아있습니다.

**Comment by violet-dev** [comment]
해당 문제는 https://github.com/project-violet/violet/commit/89a9b10e8a3e54e225e743be52004f4fd0fabc29 로 이미 고쳤습니다.
