### ISSUE TITLE
지원 가능한 다운로드 규칙 목록이 있었으면 합니다...

### ISSUE THREAD

**Issue by Jade1225** [project-violet/violet#113]
%(extractor)s/[%(artist)s][%(group)s]%(title)s[%(id)s]/%(file)s.%(ext)s
와 같은 식으로 정리해보려는데 group도 아니고 groups도 아니고 Group, Groups 전부 아니네요....
목록같은게 따로 있을까요?

**Comment by violet-dev** [comment]
[lib/component/downloadable.dart](https://github.com/project-violet/violet/blob/607c67853d23517637f9ceb7c53a4ec914af8398/lib/component/downloadable.dart#L124-L157) 에서 다운로드 규칙을 볼 수 있습니다.
다만 대부분 현재 사용되지 않아서 관련 업데이트는 필요한 상황입니다.
이 이슈는 백로그에 넣어두도록 하겠습니다 ~ 
https://github.com/project-violet/violet/issues/276
