### ISSUE TITLE
앱플레이어 사용 불가(직접 시험한 버전 중 작동불가/작동가능 앱플레이어 목록 기제합니다.)

### ISSUE THREAD

**Issue by baekho** [project-violet/violet#144]
- 앱플레이어 사용 불가 : 녹스앱플레이어 모든 버전, LD플레이어 베타9버전, 피크앱플레이어 모든버전, 블루스택 및 MSI 플레이어 모든 버전 등에서 작동불가 확인
- 정상작동 앱플레이어 : LD플레이어 4 버전)

**Comment by violet-dev** [comment]
앱플레이어가 뭔가요?

**Comment by baekho** [comment]
> 앱플레이어가 뭔가요?

윈도우의 가상머신과 비슷하게, 안드로이드를 가상머신으로 돌리는 일종의 에뮬레이터 입니다.
LD플레이어, 녹스앱플레이어, 피크앱플레이어 등 모두 안드로이드를 타 OS(주로 윈도우)에서 가상머신으로 구동하도록 하는 프로그램 입니다. :D

**Comment by violet-dev** [comment]
Hyper-V를 쓰고 있어서 제 컴퓨터에선 실행하기가 어렵네요
어떻게 안되는지 좀 더 자세하게 알려주세요
사용중인 아키텍쳐랑 운영체제 버전도 알려주세요

**Comment by baekho** [comment]
> Hyper-V를 쓰고 있어서 제 컴퓨터에선 실행하기가 어렵네요 어떻게 안되는지 좀 더 자세하게 알려주세요 사용중인 아키텍쳐랑 운영체제 버전도 알려주세요

제가 겪은 증상과 사용중인 환경은 아래와 같습니다.

-----------------------------

앱플레이어 설정 정보

앱플레이어 : LDPlayer 9
안드로이드 버전 : 9 (Android 보안 패치 수준 2018년 8월 5일)
기기설정 : SM-G965N

-----------------------------
사용자 PC 정보

Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 CPUs), ~3.2GHz
Memory: 16384MB RAM
Available OS Memory: 16222MB RAM
DirectX Version: DirectX 12
Graphic Card: Nvidia Geforce RTX 2060

-----------------------------

과정 및 증상

0. 앱플레이어 VPN 설정 및 Https 우회 설정
1. Violet 어플 설치 (from GitHub release 1.26.2)
2. Violet 실행
3. 설치할 DB 선택 (한국어 / 모든 언어 증상 동일)
4. 다운로드 진행 : 100% 완료
5. "압축푸는 중" 에서 더이상 진행 불가
p.s : 기기 자체가 프리징되거나, Violet 앱 자체가 crash 되지는 않음

**Comment by violet-dev** [comment]
가상머신이 x86_64면 lib7zr.so가 없어서 진행이 안될 수 있어요

방금 빌드 옵션 https://github.com/project-violet/violet/commit/6f90b1cea7c5b8ff27c4baa6e945d5eee7d26897 켜놨으니 https://github.com/project-violet/violet/actions/runs/2661409691 여기서 apk 다운로드 해주세요

**Comment by baekho** [comment]
> 가상머신이 x86_64면 lib7zr.so가 없어서 진행이 안될 수 있어요
> 
> 방금 빌드 옵션 [6f90b1c](https://github.com/project-violet/violet/commit/6f90b1cea7c5b8ff27c4baa6e945d5eee7d26897) 켜놨으니 https://github.com/project-violet/violet/actions/runs/2661409691 여기서 apk 다운로드 해주세요

빌드 감사합니다.
테스트를 해보았으나, 증상이 달라지지는 않았습니다.

**Comment by violet-dev** [comment]
잘 모르겠네요
그냥 7zr뺀 버전으로 빌드해볼게요
