### ISSUE TITLE
Error on IOS16.0.2

### ISSUE THREAD

**Issue by karanocave** [project-violet/violet#152]
screen keeps gray![image](https://user-images.githubusercontent.com/39995482/193434717-0378aefa-db87-4471-bb24-464f4db83cad.png)

**Comment by violet-dev** [comment]
In the case of `zh_CH`, there is a bug that a gray screen occurs. https://github.com/project-violet/violet/issues/25
Please upload the `My iPhone->Violet->log or log.txt` file in the iOS File app.

**Comment by karanocave** [comment]
2022-10-02 03:15:04.852163Z] [Error] [unhandled-error] E: Null check operator used on a null value
#0      Translations.of (package:violet/locale/locale.dart:23)
#1      _SplashPageState._firstPage (package:violet/pages/splash/splash_page.dart:412)
#2      _SplashPageState.build (package:violet/pages/splash/splash_page.dart:333)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
#13     _rootRun (dart:async/zone.dart:1391)
#14     _CustomZone.run (dart:async/zone.dart:1293)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1201)
#16     _invoke (dart:ui/hooks.dart:150)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318)
#18     _drawFrame (dart:ui/hooks.dart:115)

[2022-10-02 03:15:04.898358Z] [Error] [unhandled-error] E: Null check operator used on a null value
#0      Translations.of (package:violet/locale/locale.dart:23)
#1      _SplashPageState._firstPage (package:violet/pages/splash/splash_page.dart:412)
#2      _SplashPageState.build (package:violet/pages/splash/splash_page.dart:333)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
#13     _rootRun (dart:async/zone.dart:1391)
#14     _CustomZone.run (dart:async/zone.dart:1293)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1201)
#16     _invoke (dart:ui/hooks.dart:150)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318)
#18     _drawFrame (dart:ui/hooks.dart:115)

[2022-10-02 03:15:05.067701Z] [Error] [unhandled-error] E: Null check operator used on a null value
#0      Translations.of (package:violet/locale/locale.dart:23)
#1      _SplashPageState._firstPage (package:violet/pages/splash/splash_page.dart:412)
#2      _SplashPageState.build (package:violet/pages/splash/splash_page.dart:333)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
#13     _rootRun (dart:async/zone.dart:1391)
#14     _CustomZone.run (dart:async/zone.dart:1293)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1201)
#16     _invoke (dart:ui/hooks.dart:150)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318)
#18     _drawFrame (dart:ui/hooks.dart:115)

[2022-10-02 03:15:05.394981Z] [Info] [Http Request] GET: https://raw.githubusercontent.com/project-violet/scripts/main/hitomi_get_image_list_v3.js
[2022-10-02 03:15:05.419022Z] [Error] [unhandled-error] E: Null check operator used on a null value
#0      Translations.of (package:violet/locale/locale.dart:23)
#1      _SplashPageState._firstPage (package:violet/pages/splash/splash_page.dart:412)
#2      _SplashPageState.build (package:violet/pages/splash/splash_page.dart:333)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
#13     _rootRun (dart:async/zone.dart:1391)
#14     _CustomZone.run (dart:async/zone.dart:1293)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1201)
#16     _invoke (dart:ui/hooks.dart:150)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318)
#18     _drawFrame (dart:ui/hooks.dart:115)

**Comment by violet-dev** [comment]
check this build https://github.com/project-violet/violet/actions/runs/3167936073

**Comment by violet-dev** [comment]
Reopen if you have any problems
