### ISSUE TITLE
Apply webview to viewer 

### ISSUE THREAD

**Issue by violet-dev** [project-violet/violet#172]
## Motivation
 - There have been many attempts since 2 years ago, but could not fix the problem that the memory allocated for the image was not ejected properly.
 - These issues cause problems on many many devices.
 - This problem tends to subside with more RAM, but I don't know for sure why.
 - It seems that this problem can be completely solved by appilying a webview only.

## Plan
 - [ ] Web View UI
   - [x] Show images on webview
   - [x] Fit to width
   - [ ] Gesture integration with flutter controller
   - [ ] Image lazy loading
 - [ ] Reload logic for handling 503 error, or anyother ratelimit
 - [ ] Route logic to support multi host route (hitomi.la / e-hentai.org / exhentai.org ... or so on)
 - [ ] Integration ui and controller with viewer
 - [ ] Memory Consume Test

**Comment by DPS0340** [comment]
## Webview Tasks
- [ ] improve readme
- [x] add scripts for POSIX environments
- [x] migrate build toolchain to vite for fast build time
  - ~~or not if current setting has lower overhead for development~~
- [x] add linter (majorly eslint, with some prettier integration plugins)
- [ ] add global state management library if it needs (select one - valtio / zustand / jotai)
- [ ] add data fetcher library if it needs (tanstack query)
- [x] add tailwind css for fast & easy component styling
  - [x] enable jit mode!
- [x] refactor existing react code
- [ ] static build & copy automation using github actions (may be, need confirmation of @violet-dev)
- [ ] test automation using github actions
- [ ] implement viewer functionality
  - [ ] ??? (planning...)
