### ISSUE TITLE
북마크 내보내기 버튼 반응 없음 

### ISSUE THREAD

**Issue by green1052** [project-violet/violet#201]
아무리 눌러도 반응도 없고 로그 기록 봐도 아무것도 없습니다.

**Comment by violet-dev** [comment]
사용하시는 스마트폰 기종이 뭔가요?
아이폰에서는 북마크 내보내기 기능을 사용할 수 없습니다.

**Comment by green1052** [comment]
삼성 s22+ android 13입니다

**Comment by violet-dev** [comment]
fix: https://github.com/project-violet/violet/commit/cf108ccca5cb8f78a2b37ff88396e278e132da8b
