### ISSUE TITLE
Application isn't compatibe with arm7 

### ISSUE THREAD

**Issue by Lukumiya** [project-violet/violet#21]
Maybe add some libs to build?
![Screenshot_20200819-211410_SAI](https://user-images.githubusercontent.com/39100756/90673926-1299dd00-e261-11ea-9249-876e582d267f.png)

**Comment by violet-dev** [comment]
Try this https://github.com/project-violet/violet/releases/download/0.9.2-all-arch/app-release.apk

**Comment by Lukumiya** [comment]
now works fine, thank you!
