### ISSUE TITLE
북마크 가져오기가 안 됩니다.

### ISSUE THREAD

**Issue by anwooki** [project-violet/violet#211]
안드로이드 13문제인지 아닌지 모르겠지만 스마트폰을 바꾸고 bookmark.bd 파일을 새로운 스마트폰에서 북마크 가져오기로 가져왔는데 성공했다고 알림만 뜨고 불러와지지 않습니다. 기종은 s20플러스 입니다

**Comment by violet-dev** [comment]
로그기록 보여주세여

**Comment by violet-dev** [comment]
fix: https://github.com/project-violet/violet/commit/cf108ccca5cb8f78a2b37ff88396e278e132da8b
