### ISSUE TITLE
작가 데이터 불러오는 곳에 오류가 있는 것 같습니다.

### ISSUE THREAD

**Issue by bulb-09** [project-violet/violet#216]
![IMG_0078](https://user-images.githubusercontent.com/93650618/230782241-250bcc44-68e3-4370-a14d-4a302d0d0240.png)
![IMG_0079](https://user-images.githubusercontent.com/93650618/230782244-c80fc152-c32b-4fc0-bcbc-00273e84f40c.png)
첫번째 사진은 북마크한 작가 로딩하는 부분이고 두번째는 작가 카테고리 선택 후 들어가는 화면입니다. 두 화면 모두 플러터 UI 오류가 발생하고 있어서 아마 작가 모델 파싱 부분에서 오류가 있는 것 같아 확인해주시면 감사하겠습니다.

**Comment by violet-dev** [comment]
로그 기록 보여주세요

**Comment by bulb-09** [comment]
저거 작성할 당시에는 해당 오류가 있었는데 며칠 후에 다시 나오는 거 확인했습니다. close 처리해두겠습니다.
