### ISSUE TITLE
북마크 가져오기 권한 없음

### ISSUE THREAD

**Issue by irooooooo** [project-violet/violet#219]
북마크 가져오기 하면 권한이 없어서 실행할수 없다는데
권한 줄건지 물어보는것도 안나오고 설정에서 줄수도 없네요

안드로이드 갤럭시 노트20울트라입니다

**Comment by violet-dev** [comment]
@irooooooo 스크린샷 보여주실래요? 어떤 권한인지 알아야합니다

**Comment by irooooooo** [comment]
> @irooooooo 스크린샷 보여주실래요? 어떤 권한인지 알아야합니다

![Screenshot_20230505_204207](https://user-images.githubusercontent.com/132241057/236460604-1ea24dd0-83a3-4126-8404-6ad369e9a88d.jpg)
북마크 가져오기 누르면 이렇게 뜹니다

**Comment by violet-dev** [comment]
maybe fix: https://github.com/project-violet/violet/commit/cf108ccca5cb8f78a2b37ff88396e278e132da8b
