### ISSUE TITLE
e-hentai 북마크 연동 안됨

### ISSUE THREAD

**Issue by deric9916** [project-violet/violet#222]
Eh뷰어로 만들고 북마크 박았던거 PC 정상로그인 되는거 확인했는데
컴포넌트로 쿠키 입력하고 가져오기 했는데 아무것도 불러오지 못하고 있습니다

**Comment by TaYaKi71751** [comment]
`e-hentai.org`/`exhentai.org` 's cookie `igneous` was changed to `sk`

**Comment by violet-dev** [comment]
#277
