### ISSUE TITLE
북마크 내보내기를 해서 불러오기를 했음에도 아무것도 뜨지 않음

### ISSUE THREAD

**Issue by deric9916** [project-violet/violet#223]
폰 이동하면서 옛날 버전의 Violet에 있는 북마크 내보내기 기능으로 나온 bookmark.db파일을 다른 핸드폰에서 불러오기를 했으나 북마크에 아무것도 뜨지 않음
몇번이고 시도해보고 재기동도 해봤으나 아무것도 바뀌지 않음

**Comment by violet-dev** [comment]
fix: https://github.com/project-violet/violet/commit/cf108ccca5cb8f78a2b37ff88396e278e132da8b
