### ISSUE TITLE
LOading Script 단계에서 진행되지 않음

### ISSUE THREAD

**Issue by Mango202** [project-violet/violet#225]
![Screenshot_20230707_081951](https://github.com/project-violet/violet/assets/87093723/09278c1f-0fae-416c-9ee8-c5e999681e03)

Kst 기준 7월 6일까지는 이상 없었고 패치를 진행하지도 않았는데 7월 7일 05시부터 계속 Loading Script 단계에서 넘어가지 못합니다.

**Comment by violet-dev** [comment]
fix https://github.com/project-violet/violet/commit/ec2a9e75e975bcd7cc0e2b99d7a985c7cc5c923e
