### ISSUE TITLE
북마크가 가져오기가 안됩니다

### ISSUE THREAD

**Issue by Red12op** [project-violet/violet#231]
가져오기에 성공했다고는 뜨는데 홈에서 북마크는 여전히 0개라고 합니다

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/actions/runs/5832502934 이걸로 해보실래요?

**Comment by Red12op** [comment]
> https://github.com/project-violet/violet/actions/runs/5832502934 이걸로 해보실래요?

이걸 어떻게 사용해야하는것일까요...?

**Comment by Red12op** [comment]
> https://github.com/project-violet/violet/actions/runs/5832502934 이걸로 해보실래요?

해결됐습니다 감사합니다
