### ISSUE TITLE
App open is always a gray screen

### ISSUE THREAD

**Issue by cc1aymore** [project-violet/violet#24]
This is always the case with the previous version and this one：

![微信图片_20201009185106](https://user-images.githubusercontent.com/51788411/95575037-99e51f00-0a60-11eb-9d10-e5030be92b63.png)
![微信图片_20201009185053](https://user-images.githubusercontent.com/51788411/95575047-9ea9d300-0a60-11eb-91e9-06b40b36c9f0.jpg)

**Comment by violet-dev** [comment]
what is yout platform? ios? android?

**Comment by violet-dev** [comment]
If you are using iOS and `drawer option` is enabled, turn off.
iOS drawer was not implemented by my mistake.

https://github.com/project-violet/violet/commit/5c9f918a3585bda8255061f9ff583ef99e47b988

**Comment by cc1aymore** [comment]
> If you are using iOS and `drawer option` is enabled, turn off.
> iOS drawer was not implemented by my mistake.
> 
> [5c9f918](https://github.com/project-violet/violet/commit/5c9f918a3585bda8255061f9ff583ef99e47b988)

Not at all

**Comment by cc1aymore** [comment]
> If you are using iOS and `drawer option` is enabled, turn off.
> iOS drawer was not implemented by my mistake.
> 
> [5c9f918](https://github.com/project-violet/violet/commit/5c9f918a3585bda8255061f9ff583ef99e47b988)

I can't even get into the app. It's a gray screen

**Comment by cc1aymore** [comment]
android platform

**Comment by violet-dev** [comment]
What is your country code(IETF language tag)?
Try removing app `Completely` and reinstall

**Comment by cc1aymore** [comment]
> What is your country code(IETF language tag)?

zh-CN

**Comment by violet-dev** [comment]
I think this problem has been fixed in the latest version.
If you still have a problem, please open the issue again.
