### ISSUE TITLE
I can’t open the app.(gray screen)

### ISSUE THREAD

**Issue by ping1999** [project-violet/violet#25]
I can’t open the app.(gray screen)

**Comment by ping1999** [comment]
The last version

**Comment by ping1999** [comment]
i can open the Google play version

**Comment by violet-dev** [comment]
Try this https://github.com/project-violet/violet/releases/download/1.7.5%2B1/app-release.apk

https://github.com/project-violet/violet/commit/3ff995b1560dd3a3c1ffc346d2300863ed7c662d

**Comment by ping1999** [comment]
still gray screen

**Comment by ping1999** [comment]
![Uploading Screenshot_2020-10-28-21-26-04-023_xyz.project.violet.jpg…]()

**Comment by violet-dev** [comment]
https://github.com/violet-dev/dummy/releases/download/001/app-release.apk

Please make a copy of the execution result of this app and let me know.

ex)
```
{
     "product": "sdk_gphone_x86",
     "supportedAbis": [
          "x86"
     ],
     "supported32BitAbis": [
          "x86"
     ],
     "display": "sdk_gphone_x86-userdebug 10 QSR1.200403.001 6362371 dev-keys",
     "type": "userdebug",
     "isPhysicalDevice": false,
     "version": {
          "baseOS": "",
          "securityPatch": "2019-09-05",
          "sdkInt": 29,
          "release": "10",
          "codename": "REL",
          "previewSdkInt": 0,
          "incremental": "6362371"
     },
     "systemFeatures": [
          "android.hardware.sensor.proximity",
          "android.software.adoptable_storage",
          "android.hardware.sensor.accelerometer",
          "android.hardware.faketouch",
          "android.software.backup",
          "android.hardware.touchscreen",
          "android.hardware.touchscreen.multitouch",
          "android.software.print",
          "android.software.activities_on_secondary_displays",
          "android.software.voice_recognizers",
          "android.software.picture_in_picture",
          "android.hardware.fingerprint",
          "android.hardware.sensor.gyroscope",
          "android.software.cant_save_state",
          "android.hardware.sensor.relative_humidity",
          "android.hardware.camera.autofocus",
          "com.google.android.feature.GOOGLE_BUILD",
          "android.hardware.telephony.gsm",
          "android.hardware.audio.output",
          "android.software.verified_boot",
          "android.hardware.camera.front",
          "android.hardware.screen.portrait",
          "android.hardware.sensor.ambient_temperature",
          "android.software.home_screen",
          "android.hardware.microphone",
          "android.software.autofill",
          "android.software.securely_removes_users",
          "android.hardware.sensor.compass",
          "android.hardware.touchscreen.multitouch.jazzhand",
          "android.hardware.sensor.barometer",
          "android.software.app_widgets",
          "android.software.input_methods",
          "android.hardware.sensor.light",
          "android.hardware.vulkan.version",
          "android.software.device_admin",
          "android.hardware.camera",
          "android.hardware.screen.landscape",
          "android.hardware.ram.normal",
          "android.software.managed_users",
          "android.software.webview",
          "android.hardware.camera.capability.manual_post_processing",
          "android.hardware.camera.any",
          "android.hardware.vulkan.compute",
          "android.software.connectionservice",
          "android.hardware.touchscreen.multitouch.distinct",
          "android.hardware.location.network",
          "android.hardware.camera.ar",
          "android.software.cts",
          "android.hardware.camera.capability.manual_sensor",
          "com.google.android.apps.dialer.SUPPORTED",
          "android.hardware.camera.level.full",
          "android.hardware.wifi.direct",
          "android.software.live_wallpaper",
          "com.google.android.feature.GOOGLE_EXPERIENCE",
          "com.google.android.feature.EXCHANGE_6_2",
          "android.hardware.location.gps",
          "android.software.midi",
          "android.hardware.wifi",
          "android.hardware.location",
          "android.hardware.vulkan.level",
          "android.software.secure_lock_screen",
          "android.hardware.telephony",
          "android.software.file_based_encryption",
          null
     ],
     "manufacturer": "Google",
     "tags": "dev-keys",
     "supported64BitAbis": [],
     "bootloader": "unknown",
     "fingerprint": "google/sdk_gphone_x86/generic_x86:10/QSR1.200403.001/6362371:userdebug/dev-keys",
     "host": "abfarm-us-west1-c-0065",
     "model": "Android SDK built for x86",
     "id": "QSR1.200403.001",
     "brand": "google",
     "device": "generic_x86",
     "board": "goldfish_x86",
     "androidId": "74a04a91439e3cd7",
     "hardware": "ranchu"
}
Locale: en_US
SLocale: en_US
Locale: en_US
```

**Comment by ping1999** [comment]
`
{
     "product": "sagit",
     "supportedAbis": [
          "arm64-v8a",
          "armeabi-v7a",
          "armeabi"
     ],
     "supported32BitAbis": [
          "armeabi-v7a",
          "armeabi"
     ],
     "display": "xiaomi.eu",
     "type": "user",
     "isPhysicalDevice": true,
     "version": {
          "baseOS": "",
          "securityPatch": "2019-09-01",
          "sdkInt": 28,
          "release": "9",
          "codename": "REL",
          "previewSdkInt": 0,
          "incremental": "9.11.7"
     },
     "systemFeatures": [
          "android.hardware.sensor.proximity",
          "android.hardware.sensor.accelerometer",
          "android.hardware.faketouch",
          "android.hardware.usb.accessory",
          "android.hardware.telephony.cdma",
          "android.software.backup",
          "android.hardware.touchscreen",
          "android.hardware.touchscreen.multitouch",
          "android.software.print",
          "android.hardware.consumerir",
          "android.hardware.ethernet",
          "android.software.activities_on_secondary_displays",
          "com.google.android.feature.PIXEL_2017_EXPERIENCE",
          "android.software.voice_recognizers",
          "android.software.picture_in_picture",
          "android.hardware.fingerprint",
          "android.hardware.sensor.gyroscope",
          "android.software.cant_save_state",
          "com.google.android.feature.PIXEL_2018_EXPERIENCE",
          "android.hardware.opengles.aep",
          "android.hardware.bluetooth",
          "android.hardware.camera.autofocus",
          "com.google.android.feature.GOOGLE_BUILD",
          "android.hardware.telephony.gsm",
          "android.software.sip.voip",
          "android.hardware.usb.host",
          "android.hardware.audio.output",
          "android.software.verified_boot",
          "android.hardware.camera.flash",
          "android.hardware.camera.front",
          "android.hardware.sensor.hifi_sensors",
          "android.hardware.screen.portrait",
          "android.hardware.nfc",
          "com.google.android.feature.TURBO_PRELOAD",
          "com.nxp.mifare",
          "android.hardware.sensor.stepdetector",
          "android.software.home_screen",
          "android.hardware.microphone",
          "android.software.autofill",
          "com.google.android.feature.PIXEL_EXPERIENCE",
          "android.hardware.bluetooth_le",
          "android.hardware.sensor.compass",
          "android.hardware.touchscreen.multitouch.jazzhand",
          "android.hardware.sensor.barometer",
          "android.software.app_widgets",
          "android.software.input_methods",
          "android.hardware.sensor.light",
          "android.hardware.vulkan.version",
          "android.software.companion_device_setup",
          "android.software.device_admin",
          "com.google.android.feature.WELLBEING",
          "android.hardware.camera",
          "android.hardware.screen.landscape",
          "android.hardware.ram.normal",
          "android.software.managed_users",
          "android.software.webview",
          "android.hardware.sensor.stepcounter",
          "android.hardware.camera.any",
          "android.hardware.vulkan.compute",
          "android.software.connectionservice",
          "android.hardware.touchscreen.multitouch.distinct",
          "android.hardware.location.network",
          "android.software.cts",
          "android.software.sip",
          "com.google.android.apps.dialer.SUPPORTED",
          "android.hardware.wifi.direct",
          "android.software.live_wallpaper",
          "com.google.android.feature.GOOGLE_EXPERIENCE",
          "com.google.android.feature.EXCHANGE_6_2",
          "android.hardware.location.gps",
          "android.software.midi",
          "android.hardware.nfc.any",
          "android.hardware.nfc.hce",
          "android.hardware.wifi",
          "android.hardware.location",
          "android.hardware.vulkan.level",
          "android.hardware.telephony",
          null
     ],
     "manufacturer": "Xiaomi",
     "tags": "release-keys",
     "supported64BitAbis": [
          "arm64-v8a"
     ],
     "bootloader": "unknown",
     "fingerprint": "Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys",
     "host": "xiaomi.eu",
     "model": "MI 6",
     "id": "PKQ1.190118.001",
     "brand": "Xiaomi",
     "device": "sagit",
     "board": "msm8998",
     "androidId": "3bf80d6102317467",
     "hardware": "qcom"
}
Locale: zh_CN
SLocale: en_US
Locale: en_US

`

**Comment by ping1999** [comment]
`{
"product": "sagit",
"supportedAbis": [
"arm64-v8a",
"armeabi-v7a",
"armeabi"
],
"supported32BitAbis": [
"armeabi-v7a",
"armeabi"
],
"display": "xiaomi.eu",
"type": "user",
"isPhysicalDevice": true,
"version": {
"baseOS": "",
"securityPatch": "2019-09-01",
"sdkInt": 28,
"release": "9",
"codename": "REL",
"previewSdkInt": 0,
"incremental": "9.11.7"
},
"systemFeatures": [
"android.hardware.sensor.proximity",
"android.hardware.sensor.accelerometer",
"android.hardware.faketouch",
"android.hardware.usb.accessory",
"android.hardware.telephony.cdma",
"android.software.backup",
"android.hardware.touchscreen",
"android.hardware.touchscreen.multitouch",
"android.software.print",
"android.hardware.consumerir",
"android.hardware.ethernet",
"android.software.activities_on_secondary_displays",
"com.google.android.feature.PIXEL_2017_EXPERIENCE",
"android.software.voice_recognizers",
"android.software.picture_in_picture",
"android.hardware.fingerprint",
"android.hardware.sensor.gyroscope",
"android.software.cant_save_state",
"com.google.android.feature.PIXEL_2018_EXPERIENCE",
"android.hardware.opengles.aep",
"android.hardware.bluetooth",
"android.hardware.camera.autofocus",
"com.google.android.feature.GOOGLE_BUILD",
"android.hardware.telephony.gsm",
"android.software.sip.voip",
"android.hardware.usb.host",
"android.hardware.audio.output",
"android.software.verified_boot",
"android.hardware.camera.flash",
"android.hardware.camera.front",
"android.hardware.sensor.hifi_sensors",
"android.hardware.screen.portrait",
"android.hardware.nfc",
"com.google.android.feature.TURBO_PRELOAD",
"com.nxp.mifare",
"android.hardware.sensor.stepdetector",
"android.software.home_screen",
"android.hardware.microphone",
"android.software.autofill",
"com.google.android.feature.PIXEL_EXPERIENCE",
"android.hardware.bluetooth_le",
"android.hardware.sensor.compass",
"android.hardware.touchscreen.multitouch.jazzhand",
"android.hardware.sensor.barometer",
"android.software.app_widgets",
"android.software.input_methods",
"android.hardware.sensor.light",
"android.hardware.vulkan.version",
"android.software.companion_device_setup",
"android.software.device_admin",
"com.google.android.feature.WELLBEING",
"android.hardware.camera",
"android.hardware.screen.landscape",
"android.hardware.ram.normal",
"android.software.managed_users",
"android.software.webview",
"android.hardware.sensor.stepcounter",
"android.hardware.camera.any",
"android.hardware.vulkan.compute",
"android.software.connectionservice",
"android.hardware.touchscreen.multitouch.distinct",
"android.hardware.location.network",
"android.software.cts",
"android.software.sip",
"com.google.android.apps.dialer.SUPPORTED",
"android.hardware.wifi.direct",
"android.software.live_wallpaper",
"com.google.android.feature.GOOGLE_EXPERIENCE",
"com.google.android.feature.EXCHANGE_6_2",
"android.hardware.location.gps",
"android.software.midi",
"android.hardware.nfc.any",
"android.hardware.nfc.hce",
"android.hardware.wifi",
"android.hardware.location",
"android.hardware.vulkan.level",
"android.hardware.telephony",
null
],
"manufacturer": "Xiaomi",
"tags": "release-keys",
"supported64BitAbis": [
"arm64-v8a"
],
"bootloader": "unknown",
"fingerprint": "Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys",
"host": "xiaomi.eu",
"model": "MI 6",
"id": "PKQ1.190118.001",
"brand": "Xiaomi",
"device": "sagit",
"board": "msm8998",
"androidId": "3bf80d6102317467",
"hardware": "qcom"
}
Locale: zh_CN
SLocale: en_US
Locale: en_US`

**Comment by ping1999** [comment]
{
"product": "sagit",
"supportedAbis": [
"arm64-v8a",
"armeabi-v7a",
"armeabi"
],
"supported32BitAbis": [
"armeabi-v7a",
"armeabi"
],
"display": "xiaomi.eu",
"type": "user",
"isPhysicalDevice": true,
"version": {
"baseOS": "",
"securityPatch": "2019-09-01",
"sdkInt": 28,
"release": "9",
"codename": "REL",
"previewSdkInt": 0,
"incremental": "9.11.7"
},
"systemFeatures": [
"android.hardware.sensor.proximity",
"android.hardware.sensor.accelerometer",
"android.hardware.faketouch",
"android.hardware.usb.accessory",
"android.hardware.telephony.cdma",
"android.software.backup",
"android.hardware.touchscreen",
"android.hardware.touchscreen.multitouch",
"android.software.print",
"android.hardware.consumerir",
"android.hardware.ethernet",
"android.software.activities_on_secondary_displays",
"com.google.android.feature.PIXEL_2017_EXPERIENCE",
"android.software.voice_recognizers",
"android.software.picture_in_picture",
"android.hardware.fingerprint",
"android.hardware.sensor.gyroscope",
"android.software.cant_save_state",
"com.google.android.feature.PIXEL_2018_EXPERIENCE",
"android.hardware.opengles.aep",
"android.hardware.bluetooth",
"android.hardware.camera.autofocus",
"com.google.android.feature.GOOGLE_BUILD",
"android.hardware.telephony.gsm",
"android.software.sip.voip",
"android.hardware.usb.host",
"android.hardware.audio.output",
"android.software.verified_boot",
"android.hardware.camera.flash",
"android.hardware.camera.front",
"android.hardware.sensor.hifi_sensors",
"android.hardware.screen.portrait",
"android.hardware.nfc",
"com.google.android.feature.TURBO_PRELOAD",
"com.nxp.mifare",
"android.hardware.sensor.stepdetector",
"android.software.home_screen",
"android.hardware.microphone",
"android.software.autofill",
"com.google.android.feature.PIXEL_EXPERIENCE",
"android.hardware.bluetooth_le",
"android.hardware.sensor.compass",
"android.hardware.touchscreen.multitouch.jazzhand",
"android.hardware.sensor.barometer",
"android.software.app_widgets",
"android.software.input_methods",
"android.hardware.sensor.light",
"android.hardware.vulkan.version",
"android.software.companion_device_setup",
"android.software.device_admin",
"com.google.android.feature.WELLBEING",
"android.hardware.camera",
"android.hardware.screen.landscape",
"android.hardware.ram.normal",
"android.software.managed_users",
"android.software.webview",
"android.hardware.sensor.stepcounter",
"android.hardware.camera.any",
"android.hardware.vulkan.compute",
"android.software.connectionservice",
"android.hardware.touchscreen.multitouch.distinct",
"android.hardware.location.network",
"android.software.cts",
"android.software.sip",
"com.google.android.apps.dialer.SUPPORTED",
"android.hardware.wifi.direct",
"android.software.live_wallpaper",
"com.google.android.feature.GOOGLE_EXPERIENCE",
"com.google.android.feature.EXCHANGE_6_2",
"android.hardware.location.gps",
"android.software.midi",
"android.hardware.nfc.any",
"android.hardware.nfc.hce",
"android.hardware.wifi",
"android.hardware.location",
"android.hardware.vulkan.level",
"android.hardware.telephony",
null
],
"manufacturer": "Xiaomi",
"tags": "release-keys",
"supported64BitAbis": [
"arm64-v8a"
],
"bootloader": "unknown",
"fingerprint": "Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys",
"host": "xiaomi.eu",
"model": "MI 6",
"id": "PKQ1.190118.001",
"brand": "Xiaomi",
"device": "sagit",
"board": "msm8998",
"androidId": "3bf80d6102317467",
"hardware": "qcom"
}
Locale: zh_CN
SLocale: en_US
Locale: en_US

**Comment by ping1999** [comment]
if i change the language of the system,i can open the app

**Comment by yukkohzq** [comment]
It should be some connection with zh_CN system language, violet on my two phone (sony, oneplus) still grey screen. both are using simp chinese as system language

**Comment by MomentDerek** [comment]
my Android system is miui, language is Chinese, also cannot open the app, grey screen. I change the system language to English and it works. After I download all the language database, I change the language back to Chinese, and it still grey

**Comment by violet-dev** [comment]
Reopen when this issuse is continued.
