### ISSUE TITLE
바이러스 발견됨

### ISSUE THREAD

**Issue by evons7** [project-violet/violet#251]
Avast 모바일 버전에서 의심스럽다고 해서 바이러스 토탈 돌리니 TrendMicro-HouseCall 이란 백신에서 TROJ_GEN.R002V01JQ23이 발견 되었다 뜨는데, 신경 안쓰고 넘어 가도 될련지? 발견 버전은 이번 신 버전이요

**Comment by violet-dev** [comment]
오진입니다. 무시하셔도 상관없습니다.
