### ISSUE TITLE
PC 버전으로는 출시 생각 없으신가요?

### ISSUE THREAD

**Issue by quzilax** [project-violet/violet#258]
PC버전이 있었으면 좋겠네요.

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/tree/dev-windows 예전에 윈도우(맥 등 데스크탑)용으로 빌드를 해본적이 있었는데, 기존에 모바일 친화적으로 개발했던 터라 너무 많은 곳들 손 봐야 했었습니다 여전히 버그들도 많구요 ㅠㅠ 데스크탑 버전은 바꿔야 할 부분도 많고 시간도 개발에 시간도 오래 걸려서 아직은 모바일에 집중할 수 밖에 없을 것 같아요
