### ISSUE TITLE
Pls make a bookmark for artists and tags

### ISSUE THREAD

**Issue by Red12op** [project-violet/violet#26]
i checked stars of the artists and tags but i can't find the list anywhere...

**Comment by violet-dev2** [comment]
artists bookmark feature is already exists
you can view artists bookmark on bookmark->bookmark group(ex. Unclassified)->slide left to right
tags bookmark is not support, but we plan to support through search term favorites

**Comment by violet-dev** [comment]
This feature has already been added.
