### ISSUE TITLE
데이터베이스 다운 시 인터넷 연결오류

### ISSUE THREAD

**Issue by lsanh1018** [project-violet/violet#263]
앱 최초 설치 후 데이터베이스를 다운받으려는데 인터넷 연결오류가 뜹니다.
와이파이, 5G 데이터 환경에서도 시도해봤는데 안되네요.
![Screenshot_20231204_100840](https://github.com/project-violet/violet/assets/75327510/0a59b6cf-8109-46ce-892e-c6c2e0a855b0)

**Comment by violet-dev** [comment]
Solved by https://github.com/project-violet/violet/pull/264#issuecomment-1842890427
