### ISSUE TITLE
북마크 그룹이 작동을 안합니다.

### ISSUE THREAD

**Issue by alzkdpf12** [project-violet/violet#266]
북마크 표시를 하면 처음에 저장되는 미분류 항목에 선호작이 등록은 되었다고 뜨는데,  
표시되지 않고 기존에 있던 작품들까지 사라졌습니다.

반면, 다른 이름이 있는 북마크들의 작품들은 불러오지는 것 까지 확인했는데 무슨 상황인지 모르겠습니다. 

![1](https://github.com/project-violet/violet/assets/153432076/138f6b56-4b72-4fa0-87cf-7fb6cc4fd1c4)
![KakaoTalk_20231210_205921963](https://github.com/project-violet/violet/assets/153432076/255d1e85-8e9e-4387-912f-b4890d22f97a)
![KakaoTalk_20231210_205921963_01](https://github.com/project-violet/violet/assets/153432076/c46c1ea7-524d-40f4-bf3e-965aebac399b)
![KakaoTalk_20231210_205921963_02](https://github.com/project-violet/violet/assets/153432076/e825c156-1438-457e-9ecb-523e91d8a108)

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/commit/e284f00d665962e6f8c7db3fd5cabfc9928b2f6a 로 고쳤습니다.

**Comment by alzkdpf12** [comment]
제가 ios를 사용 중인데 올라온 파일을 다시 다운받아서 설치하면 해결 되는 것인가요?

2023년 12월 10일 (일) 오후 10:12, koromo ***@***.***>님이 작성:

**Comment by alzkdpf12** [comment]
일단 지금 올라와있는 payload.ipa 파일 다운받아 재설치하고 있습니다...!

**Comment by alzkdpf12** [comment]
제가 코딩을 잘 몰라서 그러는데 링크 걸어놓으신 거를 어떻게 활용해야 할까요...? ㅜㅜ

**Comment by violet-dev** [comment]
아 넵 https://github.com/project-violet/violet/releases/download/1.29.2/Payload.ipa 요거 사용하시면 됩니다.
방금전에 릴리즈했어요
