### ISSUE TITLE
App Blank Screen

### ISSUE THREAD

**Issue by EriTang** [project-violet/violet#27]
App v1.7.3 Blank Screen in iPhone12 Pro Max(iOS14.2)
![5C3AB882-D3CA-48A7-81E9-7E227159E0A5](https://user-images.githubusercontent.com/73655702/102001107-1a5a2180-3d29-11eb-8569-8784d0895940.png)

**Comment by violet-dev** [comment]
I think this issue is same as https://github.com/project-violet/violet/issues/25
I couldn't solve it because I didn't have time
I'll find a solution soon.

**Comment by EriTang** [comment]
After testing, it was found that only Chinese environment could not be operated normally, but English and Korean environment could be operated normally

**Comment by EriTang** [comment]
But I can manually change the APP in English and Korean system environment in language is Chinese, can be normal use

**Comment by EriTang** [comment]
// Full Chinese support for CN, TW, and HK
supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh'), // generic Chinese 'zh'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese 'zh_Hans'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese 'zh_Hant'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'CN'), // 'zh_Hans_CN'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'TW'), // 'zh_Hant_TW'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'HK'), // 'zh_Hant_HK'
],

This is what I saw on the official Doc of Flutter, hopefully this will help

**Comment by violet-dev** [comment]
Thank you @EriTang 
I'll try thay

**Comment by violet-dev** [comment]
Reopen when this issue is continued
