### ISSUE TITLE
iOS violet 앱 다운로드 규칙중에 작품 제목으로 저장되도록 하려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by MoroboshiKirari** [project-violet/violet#379]
현재는 품번으로만 저장되서 제목을 바꾸기가 귀찮은데
따로 방법은 없나요?

**Comment by violet-dev** [comment]
경로 규칙에 원하는 부분에다가 %(title)s를 입력하면 됩니다.

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/issues/113

**Comment by MoroboshiKirari** [comment]
답장 감사드립니다. 추가로 질문이 있습니다.
Pure Search와 violet server 사용은 무슨 기능인가요?

2024년 2월 3일 (토) 09:53, koromo ***@***.***>님이 작성:
