### ISSUE TITLE
[Solved but, not in released yet] When push Database > Switching button, stuck at "loading bookmark..." screen at 1.31.1

### ISSUE THREAD

**Issue by TaYaKi71751** [project-violet/violet#407]
at https://github.com/project-violet/violet/tree/1.31.1
![Screenshot_20240219_114039](https://github.com/project-violet/violet/assets/56256195/d67a518b-0b65-4b4a-bba7-27b2dc7b15d7)
![Screenshot_20240219_114049](https://github.com/project-violet/violet/assets/56256195/bb29b21e-1045-42bc-ac0c-5585d1a7e15e)

**Comment by TaYaKi71751** [comment]
need triage with build from dev branch

**Comment by TaYaKi71751** [comment]
It works well with
 build from dev branch 
 [Build](https://github.com/TaYaKi71751/violet-git/releases/tag/1.31.1-fbc32f259047df5912f1e500c99431f5d4b34d5f) of [fbc32f259047df5912f1e500c99431f5d4b34d5f](https://github.com/project-violet/violet/commit/fbc32f259047df5912f1e500c99431f5d4b34d5f)

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/pull/403
