### ISSUE TITLE
갤럭시 데이터베이스 다운 안됨

### ISSUE THREAD

**Issue by Gkqls7** [project-violet/violet#409]
휴대폰을 새로 바꾸고 다시 들어가려고 하는데 처음 데이터 베이스 다운 화면에서 다운로드가 클릭이 안됨.
![Screenshot_20240401_165429](https://github.com/project-violet/violet/assets/165645338/b3254b64-4f3d-42eb-a9ce-123cc223c734)

**Comment by Gkqls7** [comment]
이거 중국어 같은 경우는 다운로드가 클릭이 되는데 한국어로는 다운로드 버튼이 클릭이 되지 않습니다.

**Comment by violet-dev** [comment]
duplicated by https://github.com/project-violet/violet/issues/392
