### ISSUE TITLE
대사검색기 관련 질문드립니다

### ISSUE THREAD

**Issue by 6fce01** [project-violet/violet#422]
혹시 데이터베이스 업데이트하실 계획이 있나요? 대사검색이 앱에서는 서버때문에 안되도 컴퓨터에선 잘되더라구요..
마음같아선 제가 어떻게 해보고 싶은데 많이 힘들고 어려워 보여서 여쭤봅니다

**Comment by violet-dev** [comment]
디비 업데이트안한지 1년이 넘었네요
이거 1년치면 보름~한 달 정도 걸릴 듯 합니다

**Comment by violet-dev** [comment]
작업중이고 대략 20일정도 걸릴 예정입니다.

**Comment by 6fce01** [comment]
정말 감사합니다..

**Comment by violet-dev** [comment]
좀 늦었네요
https://github.com/project-violet/violet-message-search-local/releases/tag/2024.07.27 요거 쓰시면 됩니다!
2024년 6월 말까지 포함되어있습니다.

**Comment by GrapeMax** [comment]
선생님 안녕하세요.

로컬버전을 잘 사용하고 있습니다. 항상 감사합니다.

이번에 새로 업데이트 해주신 merged.json을 새로 넣었는데,

run.bat은 잘 실행이 되나 run-fscm.bat는 실행하면 바로 종료되는 현상이 발생합니다.

방법이 있을까요..

**Comment by violet-dev** [comment]
simdjson이 4gb 이상 json file을 지원하지 않아서 발생한 문제로 파악했습니다.
json 파일을 partitioning하여 로드할 수 있도록 변경할게요

위 문제 해결해도 peak memory가 32gb 가까이 되어서 좀 더 최적화 해야 할 것 같습니다.

**Comment by violet-dev** [comment]
일단 https://github.com/project-violet/violet-message-search-local/releases/download/2024.07.27/fscm.exe 요거 사용해주세요
로딩이 느리지만 동작 확인했습니다.

**Comment by GrapeMax** [comment]
정말 감사합니다

**Comment by III1119** [comment]
다운로드 링크가 날아간거 같은데 어떻게 받아야 할까요?

**Comment by violet-dev** [comment]
@III1119 https://github.com/project-violet/violet/releases/download/MessageSearch/dist.7z 로 받으시면 됩니다.
