### ISSUE TITLE
[Feature Request] Push To F-Droid

### ISSUE THREAD

**Issue by grravity** [project-violet/violet#6]
Suggesting pushing the app onto F-Droid.

**Comment by violet-dev** [comment]
I heard that f-droid is a platform that avoids Google.
Can I register using analystics and without using gpl?

**Comment by grravity** [comment]
No, and I would highly recommend using any analytics or other proprietary dependencies in a possibly great app please.

https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by violet-dev** [comment]
I will consider applying.
See https://github.com/project-violet/violet/pull/19

**Comment by grravity** [comment]
Glad to hear!

**Comment by grravity** [comment]
Any further considerations? Hope to see it, would be a make or break thing as far as me using the app personally. Thanks :blush:
