### ISSUE TITLE
App launches in korean

### ISSUE THREAD

**Issue by ChillHorse** [project-violet/violet#7]
For some reason the app was launched in korean and still has plenty of elements that won't take the English translation. My phones system language is German between

**Comment by violet-dev** [comment]
Try this https://github.com/project-violet/violet/releases/download/0.7.6lf/app-release.apk
You must remove app before installing.

**Comment by ChillHorse** [comment]
That fixed the initial loading, yes. But there's still a bunch of korean being used
![Screenshot_20200719-082108](https://user-images.githubusercontent.com/17539404/87868696-f7555c80-c998-11ea-9f48-e01a1b5e594f.png)

**Comment by rollrat** [comment]
예=yes, 아니요=no
tag rebuild has not been implemented yet. I will fix it.

**Comment by violet-dev** [comment]
예=yes, 아니요=no
tag rebuild has not been implemented yet. I will fix it.
