### ISSUE TITLE
가로화면시 두쪽보기 기능 추가가 가능할까요?

### ISSUE THREAD

**Issue by FuukaHikaru** [project-violet/violet#77]
좋은 어플리케이션 만들어주셔서 감사합니다.

갤럭시 폴드 2를 사용중입니다.
두 페이지를 한꺼번에 볼 수 있었으면 좋겠습니다.
기능 중에 두쪽보기가 있을 것 같은데 찾아봐도 보이지가 않습니다...

감사합니다.

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/issues/307
저도 이제 테블릿을 구매해서 조만간 배송되면 본격적으로 뷰어 개선 예정입니다.

**Comment by violet-dev** [comment]
https://github.com/project-violet/violet/pull/380
