### ISSUE TITLE
기능 추가 건의

### ISSUE THREAD

**Issue by green1052** [project-violet/violet#78]
1. 검색 옵션 유지 기능
![Screenshot_20210731-024032](https://user-images.githubusercontent.com/34261355/127691426-ff598ae7-b549-4eae-aa39-a94e6f98b472.jpg)

나갔다가 다시 들어오면 초기화 되어 있습니다.

2. 뷰어 터치로 다음 그림 넘어가는거 끄기
보는 도중 터치하면 다음 그림으로 넘어가 불편합니다.

그리고 검색창에 스페이스 바 모양은 무엇인가요?
눌러도 아무 반응이 없네요

**Comment by violet-dev** [comment]
2번 문제는 뷰어 설정에서 오버레이 버튼 설정을 끄면 됩니다.
