### ISSUE TITLE
기능 추가 건의

### ISSUE THREAD

**Issue by green1052** [project-violet/violet#79]
1. 브라우저에서 앱 열 수 있게
지원되는 링크 추가

2. 조회수 기준으로 보는 기능

있으면 좋을거 같습니다
감자합니다

**Comment by violet-dev** [comment]
1. 추가하겠습니다.
2. 조회수 기준 정렬 기능은 필터 페이지에 Population 옵션이 있으니 참고바랍니다.

**Comment by green1052** [comment]
감사합니다
