### ISSUE TITLE
어플 실행시 보라색 화면에서 넘어가지 않는 현상?

### ISSUE THREAD

**Issue by ojhyu** [project-violet/violet#96]
어플실행하고 V 로고가 나오는 화면에서 넘어가질 않는데 어떻게 해결해야되나요?
![image](https://user-images.githubusercontent.com/94902125/143009982-7a8df3a7-5971-4e31-9be6-ce790ad96599.png)
이 화면에서 넘어가질 않습니다.

**Comment by violet-dev** [comment]
기기 정보 알려주세요
