### ISSUE TITLE
Unhandled-error 띄우면서 이미지 로딩이 안 됩니다

### ISSUE THREAD

**Issue by Mango202** [project-violet/violet#99]
일단 버전은 최신 버전이고..

주말부터 일부 페이지가 보여지지 않는 현상이 시작되더니 이제는 모든 이미지를 볼 수 없습니다.

다운로드해보면 제목에 [Error] Unhandled-error라고 나오고 해당 페이지는 비어 있으며 이미지로 띄울 수 없다(~.webp is empty and cannot be loaded as an image.)라고 나옵니다.

**Comment by violet-dev** [comment]
https://github.com/project-violet/hitomi-reversing
https://github.com/project-violet/scripts/commit/9c296f904d1de5b529abb9679124ddcabf8e66c3
